# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.cache/wt [current_project]
set_property parent.project_path D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/Mycode/vivadoCode/5.memory/5.1data_ram/lcd_module.dcp
set_property used_in_implementation false [get_files D:/Mycode/vivadoCode/5.memory/5.1data_ram/lcd_module.dcp]
read_verilog -library xil_defaultlib D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/sources_1/new/data_ram_display.v
read_ip -quiet D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]
set_property is_locked true [get_files D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/sources_1/ip/data_ram/data_ram.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/constrs_1/new/data_ram.xdc
set_property used_in_implementation false [get_files D:/Mycode/vivadoCode/5.memory/5.1data_ram/5.1data_ram.srcs/constrs_1/new/data_ram.xdc]


synth_design -top data_ram_display -part xc7a200tfbg676-2


write_checkpoint -force -noxdef data_ram_display.dcp

catch { report_utilization -file data_ram_display_utilization_synth.rpt -pb data_ram_display_utilization_synth.pb }
