# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.cache/wt [current_project]
set_property parent.project_path D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/Mycode/vivadoCode/6.single_cycle_cpu/lcd_module.dcp
set_property used_in_implementation false [get_files D:/Mycode/vivadoCode/6.single_cycle_cpu/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/adder.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/alu.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/data_ram.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/inst_rom.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/regfile.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/single_cycle_cpu.v
  D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/sources_1/new/single_cycle_cpu_display.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/constrs_1/new/single_cycle_cpu.xdc
set_property used_in_implementation false [get_files D:/Mycode/vivadoCode/6.single_cycle_cpu/6.single_cycle_cpu.srcs/constrs_1/new/single_cycle_cpu.xdc]


synth_design -top single_cycle_cpu_display -part xc7a200tfbg676-2


write_checkpoint -force -noxdef single_cycle_cpu_display.dcp

catch { report_utilization -file single_cycle_cpu_display_utilization_synth.rpt -pb single_cycle_cpu_display_utilization_synth.pb }
